backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

site_url: https://przemekmiros.pl/

media_folder: "src/assets/img/" # Media files will be stored in the repo under assets/images/uploads
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /images/uploads


collections:
  #Global Settings
  - name: "global-settings"
    label: "Ustawienia globalne"
    slug: "{{slug}}"
    files:
      - label: "Global Settings"
        name: "global"
        file: "src/admin/global.json"
        fields:
          - { label: "Logo", name: "logo", widget: "image", required: true }
# Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Wpisy blogowe" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g.title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Obraz", name: "thumbnail", widget: "image"}
      - {label: "Kolor", name: "color", widget: "string"}
      - {label: "Tagi", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  # Our pages e.g. About
  - name: "realizacje"
    label: "Realizacje"
    folder: "src/realizacje"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/realisation.njk"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Obraz", name: "thumbnail", widget: "image"}
      - {label: "Tagi", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
